(()=>{
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({ '&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;' }[m]));
function ensureOnline(){let w=$('gslOnlineUsers');if(w)return w;w=document.createElement('div');w.id='gslOnlineUsers';w.className='gsl-online-users';w.innerHTML='<span class=\"live-pulse\"></span><b id=\"gslOnlineCount\">—</b><span>usuarios en línea</span>';document.body.appendChild(w);return w}
async function heartbeat(){ensureOnline();let sid=localStorage.getItem('gsl_sid');if(!sid){sid=(crypto.randomUUID?.()||Math.random().toString(36).slice(2)).replace(/-/g,'');localStorage.setItem('gsl_sid',sid)}try{const r=await fetch('/api/presence?sid='+encodeURIComponent(sid),{cache:'no-store'}),j=await r.json();if(j.sid)localStorage.setItem('gsl_sid',j.sid);$('gslOnlineCount').textContent=Number(j.online||1).toLocaleString('es-PE')}catch{$('gslOnlineCount').textContent='—'}}
function fuelUi(){const old=$('freightDiesel');if(!old)return;const wrap=old.closest('.freight-load-field');if(!wrap)return;wrap.innerHTML='<label>Diésel automático de origen</label><div id=\"freightFuelAuto\" class=\"fuel-auto-box\">Selecciona el lugar de salida para consultar OSINERGMIN.</div><details class=\"advanced-option\"><summary>⚙ Ajuste avanzado</summary><label for=\"freightDiesel\">Precio manual S/ por galón</label><div class=\"number-unit\"><input id=\"freightDiesel\" type=\"number\" min=\"8\" max=\"30\" step=\"0.01\" value=\"15.50\"><span>S//gal</span></div><small>Solo se usa si activas el valor manual.</small><label><input id=\"freightManualFuel\" type=\"checkbox\"> Usar precio manual</label></details>'}
let fuelTimer=0;async function refreshFuel(){const origin=$('freightOrigin')?.value?.trim();const box=$('freightFuelAuto');if(!origin||!box)return;box.innerHTML='Consultando diésel cercano…';try{const r=await fetch('/api/fuel?origin='+encodeURIComponent(origin),{cache:'no-store'}),j=await r.json();if(!j.ok)throw 0;box.innerHTML=`<b>S/ ${Number(j.price).toFixed(2)}/gal</b><span>${esc(j.station||'—')}</span><small>${esc(j.location||'')} · ${esc(j.source||'')}</small>`;box.dataset.price=j.price}catch{box.textContent='No se pudo consultar OSINERGMIN; el cálculo usará referencia automática de respaldo.'}}
function hookOrigin(){['freightOriginDistrict','freightOriginProvince','freightOriginRegion'].forEach(id=>$(id)?.addEventListener('change',()=>{clearTimeout(fuelTimer);fuelTimer=setTimeout(refreshFuel,350)}));}
function patchFreight(){const b=$('freightCalc');if(!b)return;const nb=b.cloneNode(true);b.replaceWith(nb);nb.addEventListener('click',async()=>{const origin=$('freightOrigin')?.value.trim(),destination=$('freightDestination')?.value.trim(),tons=+$('freightTons')?.value||0;if(!origin||!destination||tons<=0){$('freightResult').textContent='Selecciona salida, llegada y toneladas.';return}$('freightResult').textContent='Calculando ruta, combustible y flete…';let q=`/api/freight?origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}&tons=${tons}`;if($('freightManualFuel')?.checked)q+=`&diesel=${encodeURIComponent(+$('freightDiesel').value||15.5)}`;try{const r=await fetch(q,{cache:'no-store'}),j=await r.json();if(!j.ok)throw Error(j.error||'No disponible');$('freightResult').innerHTML=`<b>${esc(origin)} → ${esc(destination)}</b><div class=\"freight-metrics\"><span>Distancia <b>${Math.round(j.distanceKm)} km</b></span><span>Carga <b>${Number(j.tons).toFixed(1)} t</b></span><span>Tarifa/kg <b>S/ ${Number(j.rateKg).toFixed(3)}</b></span><span>Rango/kg <b>S/ ${Number(j.lowRateKg).toFixed(3)} – ${Number(j.highRateKg).toFixed(3)}</b></span><span>Flete promedio <b>S/ ${Math.round(j.mid).toLocaleString('es-PE')}</b></span><span>Diésel <b>S/ ${Number(j.diesel).toFixed(2)}/gal</b></span></div><div class=\"fuel-used\"><b>Combustible usado</b><span>${esc(j.fuel?.station||'Referencia')}</span><small>${esc(j.fuel?.location||'')} · ${esc(j.fuel?.source||'')}</small></div><small>${esc(j.note||'')}</small>`}catch(e){$('freightResult').textContent='No se pudo calcular. Verifica origen, destino y conexión.'}})}
function patchEmergencyLegend(){const el=$('emergencyLegend');if(el)el.innerHTML='<b>ESTADO DE EMERGENCIA PCM</b><span><i style=\"background:#d83a3a\"></i> Vigente: más de 10 días</span><span><i style=\"background:#ef8c32\"></i> Por vencer: 1–10 días</span><span><i style=\"background:#7a8790\"></i> Sin estado vigente</span><small>Haz clic en el distrito para ver decreto, causal, fecha de término y días restantes.</small>'}
window.addEventListener('DOMContentLoaded',()=>{ensureOnline();heartbeat();setInterval(heartbeat,45000);fuelUi();hookOrigin();setTimeout(()=>{patchFreight();refreshFuel();patchEmergencyLegend()},1000)});
})();