(()=>{
'use strict';
const PRODUCTS=[
'Aceituna','Aceituna negra','Aceituna verde','Aceite de oliva','Ajo','Alcachofa','Alfalfa','Algodón','Arroz','Arveja','Arveja verde','Avena','Banano','Cacao','Café','Camote','Caña de azúcar','Cebada','Cebolla','Cebolla roja','Cebolla amarilla','Chirimoya','Choclo','Cítricos','Espárrago','Frijol','Frijol canario','Frijol castilla','Fresa','Granada','Haba','Haba verde','Limón','Lúcuma','Maíz','Maíz amarillo duro','Maíz amiláceo','Mandarina','Mango','Manzana','Maracuyá','Naranja','Olivo','Orégano','Palta','Papa','Papa blanca','Papa amarilla','Papaya','Páprika','Pecana','Pepino','Pimiento','Piña','Plátano','Quinua','Sandía','Tangelo','Tomate','Trigo','Uva','Yuca','Zanahoria','Zapallo'
];
const MARKET_TERMS=['Gran Mercado Mayorista de Lima','Mercado Mayorista de Productores de Lima','Mercado Mayorista de Arequipa','Mercado San Camilo','Mercado Avelino Cáceres','Mercado Modelo de Piura','Mercado Moshoqueque','Mercado Mayorista de Trujillo','Mercado Hermelinda','Mercado de Chiclayo'];
const TOPIC_TERMS=['precio','ingreso de productos','siembra','cosecha','campaña agrícola','rendimiento','flete','mercado mayorista','abastecimiento','oferta','demanda'];
let UBIGEO=[];
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function loadUbigeo(){
 try{const r=await fetch('./ubigeo_inei_2025.csv',{cache:'force-cache'});if(!r.ok)return;const t=await r.text();const lines=t.split(/\r?\n/).filter(Boolean);const head=lines.shift().split(',').map(x=>x.replace(/^"|"$/g,'').trim());const idx=(...names)=>{for(const n of names){const i=head.findIndex(h=>norm(h)===norm(n));if(i>=0)return i}return -1};const ir=idx('departamento','region','dpto'),ip=idx('provincia'),id=idx('distrito');UBIGEO=lines.map(line=>{const cols=line.match(/("(?:[^"]|"")*"|[^,]+)/g)||[];const clean=cols.map(x=>x.replace(/^"|"$/g,'').replace(/""/g,'"').trim());return {region:clean[ir]||'',province:clean[ip]||'',district:clean[id]||''}}).filter(x=>x.district);
 }catch(e){console.warn('Ubigeo autocomplete:',e)}
}
function unique(arr,key=x=>x){const seen=new Set();return arr.filter(x=>{const k=norm(key(x));if(!k||seen.has(k))return false;seen.add(k);return true})}
function locationSuggestions(q,limit=18){const n=norm(q);if(!n)return [];return unique(UBIGEO.filter(x=>norm(`${x.district} ${x.province} ${x.region}`).includes(n)).slice(0,limit),x=>`${x.district}|${x.province}|${x.region}`).map(x=>({value:`${x.district}, ${x.province}, ${x.region}`,title:x.district,meta:`${x.province} · ${x.region}`,icon:'📍'}));}
function productSuggestions(q,limit=18){const n=norm(q);const all=[...PRODUCTS,...MARKET_TERMS,...TOPIC_TERMS];return all.filter(x=>!n||norm(x).includes(n)).slice(0,limit).map(x=>({value:x,title:x,meta:PRODUCTS.includes(x)?'Producto agrícola':MARKET_TERMS.includes(x)?'Mercado':'Tema de consulta',icon:PRODUCTS.includes(x)?'🌱':MARKET_TERMS.includes(x)?'🏬':'🔎'}));}
function mixedSuggestions(q,limit=18){return unique([...locationSuggestions(q,12),...productSuggestions(q,12)],x=>x.value).slice(0,limit)}
function classify(el){const id=(el.id||'').toLowerCase(),ph=(el.placeholder||'').toLowerCase(),cl=(el.className||'').toString().toLowerCase();if(el.type==='number'||el.type==='range'||el.type==='hidden')return null;if(id==='marketproduct'||id==='agrisignalquery'||/producto|cultivo|precio|cosecha|siembra/.test(ph))return 'product';if(id==='histsearch'||/lugar|ciudad|distrito|provincia|region|direcci|origen|destino|parada/.test(ph)||cl.includes('route-stop-input'))return 'location';if(/buscar|search|consulta/.test(id+ph))return 'mixed';return null}
function attach(el,kind){if(!el||el.dataset.smart166==='1'||el.closest('.route-search-row')&&['routeOrigin','routeDestination'].includes(el.id))return;el.dataset.smart166='1';el.setAttribute('autocomplete','off');const parent=el.parentElement;const wrap=document.createElement('div');wrap.className='gsl-smart-wrap';parent.insertBefore(wrap,el);wrap.appendChild(el);const box=document.createElement('div');box.className='gsl-smart-list';wrap.appendChild(box);const hint=document.createElement('div');hint.className='gsl-smart-hint';hint.textContent=kind==='product'?'Escribe para ver productos y mercados disponibles.':'Escribe para ver ubicaciones disponibles.';wrap.appendChild(hint);let active=-1;
 const render=()=>{const q=el.value.trim();if(q.length<1){box.classList.remove('show');box.innerHTML='';return}let arr=kind==='product'?productSuggestions(q):kind==='location'?locationSuggestions(q):mixedSuggestions(q);if(!arr.length){box.innerHTML='<div class="gsl-smart-empty">Sin coincidencias locales. Continúa escribiendo o usa el buscador del módulo.</div>';box.classList.add('show');return}box.innerHTML=arr.map((x,i)=>`<button type="button" class="gsl-smart-item" data-i="${i}"><span>${x.icon||'•'}</span><span><b>${esc(x.title)}</b><small>${esc(x.meta||'')}</small></span></button>`).join('');box.classList.add('show');active=-1;box.querySelectorAll('.gsl-smart-item').forEach(b=>b.onclick=()=>{const x=arr[+b.dataset.i];el.value=x.value;box.classList.remove('show');el.dispatchEvent(new Event('change',{bubbles:true}));});};
 el.addEventListener('input',render);el.addEventListener('focus',render);el.addEventListener('keydown',e=>{const items=[...box.querySelectorAll('.gsl-smart-item')];if(!items.length)return;if(e.key==='ArrowDown'){e.preventDefault();active=(active+1)%items.length}else if(e.key==='ArrowUp'){e.preventDefault();active=(active-1+items.length)%items.length}else if(e.key==='Enter'&&active>=0){e.preventDefault();items[active].click();return}else if(e.key==='Escape'){box.classList.remove('show');return}else return;items.forEach((x,i)=>x.classList.toggle('active',i===active));items[active]?.scrollIntoView({block:'nearest'});});
 document.addEventListener('click',e=>{if(!wrap.contains(e.target))box.classList.remove('show')});
}
function scan(root=document){root.querySelectorAll('input[type="text"],input:not([type]),input[type="search"]').forEach(el=>{const k=classify(el);if(k)attach(el,k)})}
async function init(){await loadUbigeo();scan();const mo=new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===1){if(n.matches?.('input')){const k=classify(n);if(k)attach(n,k)}scan(n)}})));mo.observe(document.body,{childList:true,subtree:true});window.GeoSismosSmartInputs={scan,products:PRODUCTS,locations:()=>UBIGEO};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
