(()=>{
'use strict';
const $=id=>document.getElementById(id);
const RS={mode:null,start:null,end:null,startLayer:null,endLayer:null,searchTimers:{},searchAbort:{}};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function poiIcon(type){const t=String(type||'').toLowerCase();if(t.includes('restaurante')||t.includes('comida'))return '🍽️';if(t.includes('hotel')||t.includes('alojamiento'))return '🏨';if(t.includes('comercial')||t.includes('negocio'))return '🛍️';if(t.includes('calle')||t.includes('dirección'))return '🛣️';if(t.includes('transporte')||t.includes('terminal'))return '🚌';if(t.includes('salud'))return '🏥';if(t.includes('educación'))return '🎓';return '📍';}
function coord(p){return p?`${(+p.lat).toFixed(6)},${(+p.lon).toFixed(6)}`:''}
function routeArg(id,p){const el=$(id);return p?coord(p):(el?.value.trim()||'')}
function clearMode(){RS.mode=null;document.querySelectorAll('.pick-map-btn').forEach(b=>b.classList.remove('map-pick-active'));if($('routePickHint'))$('routePickHint').textContent='';}
function updatePoint(kind,p,label){RS[kind]=p;const input=$(kind==='start'?'routeOrigin':'routeDestination');if(input){input.dataset.coord=coord(p);input.value=label||coord(p);} drawPoint(kind,p,label||coord(p));}
function drawPoint(kind,p,label){const map=window.GSL_ROAD_MAP;if(!map||!window.L||!p)return;const prop=kind==='start'?'startLayer':'endLayer';if(RS[prop])map.removeLayer(RS[prop]);const c=kind==='start'?'#18c995':'#ef5656';RS[prop]=L.circleMarker([p.lat,p.lon],{radius:9,color:'#fff',weight:3,fillColor:c,fillOpacity:1}).bindTooltip(kind==='start'?'INICIO':'FIN',{permanent:false,direction:'top'}).bindPopup(`<b>${kind==='start'?'Inicio':'Fin'}</b><br>${esc(label||coord(p))}`).addTo(map);}
async function reverseName(p){try{const r=await fetch(`/api/place-reverse?lat=${encodeURIComponent(p.lat)}&lon=${encodeURIComponent(p.lon)}`);const j=await r.json();return j.ok?(j.label||coord(p)):coord(p)}catch{return coord(p)}}
async function pickMap(kind){const map=window.GSL_ROAD_MAP;if(!map)return;RS.mode=kind;document.querySelectorAll('.pick-map-btn').forEach(b=>b.classList.toggle('map-pick-active',b.dataset.kind===kind));$('routePickHint').textContent=`Haz clic en el mapa para marcar el ${kind==='start'?'PUNTO DE INICIO':'PUNTO FINAL'}.`;map.getContainer().style.cursor='crosshair';}
function bindMapPicker(){const map=window.GSL_ROAD_MAP;if(!map||map.__gslV162Pick)return;map.__gslV162Pick=true;map.on('click',async e=>{if(!RS.mode)return;const kind=RS.mode,p={lat:e.latlng.lat,lon:e.latlng.lng};const input=$(kind==='start'?'routeOrigin':'routeDestination');if(input){input.value='Obteniendo nombre del lugar…';input.dataset.coord=coord(p);}drawPoint(kind,p,coord(p));clearMode();map.getContainer().style.cursor='';const label=await reverseName(p);updatePoint(kind,p,label);});}
async function searchPlaces(kind,q){const box=$(kind==='start'?'routeOriginSuggestions':'routeDestinationSuggestions');if(!box)return;if(!q||q.length<3){box.classList.remove('show');box.innerHTML='';return;}try{RS.searchAbort[kind]?.abort();const ctl=new AbortController();RS.searchAbort[kind]=ctl;const pos=window.__gslUserLocation;const qs=new URLSearchParams({q});if(pos?.lat&&pos?.lon){qs.set('lat',pos.lat);qs.set('lon',pos.lon)}const r=await fetch(`/api/place-search?${qs}`,{signal:ctl.signal});const j=await r.json();const a=j.results||[];box.innerHTML=a.length?a.map((x,i)=>`<button class="route-suggestion" data-i="${i}"><span class="route-poi-icon">${poiIcon(x.type)}</span><span><b>${esc(x.name||x.label)}</b><small>${esc(x.type||'Lugar')} · ${esc(x.label||'')}</small></span></button>`).join(''):'<div class="route-suggestion"><small>Sin coincidencias. Prueba una calle, hotel, restaurante, plaza, mercado, negocio o distrito.</small></div>';box.classList.add('show');box.querySelectorAll('button[data-i]').forEach(b=>b.onclick=async()=>{const x=a[+b.dataset.i];let p={lat:+x.lat,lon:+x.lon},label=x.label||x.name;if((!Number.isFinite(p.lat)||!Number.isFinite(p.lon))&&x.placeId){try{const rr=await fetch(`/api/place-detail?id=${encodeURIComponent(x.placeId)}`),dd=await rr.json();if(dd.ok){p={lat:+dd.lat,lon:+dd.lon};label=dd.label||label;}}catch{}}if(!Number.isFinite(p.lat)||!Number.isFinite(p.lon))return;updatePoint(kind,p,label);box.classList.remove('show');window.GSL_ROAD_MAP?.setView([p.lat,p.lon],15);});}catch(e){if(e.name!=='AbortError'){box.innerHTML='';box.classList.remove('show')}}}
function wireSearch(kind){const input=$(kind==='start'?'routeOrigin':'routeDestination');if(!input)return;input.addEventListener('input',()=>{input.dataset.coord='';RS[kind]=null;clearTimeout(RS.searchTimers[kind]);RS.searchTimers[kind]=setTimeout(()=>searchPlaces(kind,input.value.trim()),320)});input.addEventListener('focus',()=>{if(input.value.trim().length>=3)searchPlaces(kind,input.value.trim())});}
async function useGps(){if(!navigator.geolocation){$('routePickHint').textContent='Este dispositivo no ofrece geolocalización.';return;}$('routePickHint').textContent='Solicitando ubicación…';navigator.geolocation.getCurrentPosition(async pos=>{const p={lat:pos.coords.latitude,lon:pos.coords.longitude};const label=await reverseName(p);updatePoint('start',p,`Mi ubicación · ${label}`);window.GSL_ROAD_MAP?.setView([p.lat,p.lon],13);$('routePickHint').textContent='Origen establecido con GPS.';},()=>{$('routePickHint').textContent='No se pudo obtener la ubicación. Revisa el permiso del navegador.';},{enableHighAccuracy:true,timeout:10000,maximumAge:60000});}
async function drawRoute(){const origin=routeArg('routeOrigin',RS.start),destination=routeArg('routeDestination',RS.end);if(!origin||!destination){$('routeSummary').textContent='Selecciona o marca en el mapa un punto de inicio y un punto final.';return;}const stops=[...document.querySelectorAll('.route-stop-input')].map(x=>x.value.trim()).filter(Boolean);$('routeSummary').textContent='Calculando ruta vial…';try{const r=await fetch(`/api/route?origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}&stops=${encodeURIComponent(stops.join('|'))}`,{cache:'no-store'}),j=await r.json();if(!j.ok)throw Error(j.error||'Ruta no disponible');const map=window.GSL_ROAD_MAP;if(window.__gslV162RouteLayer)map.removeLayer(window.__gslV162RouteLayer);if(window.__gslV162RouteMarkers)map.removeLayer(window.__gslV162RouteMarkers);window.__gslV162RouteLayer=L.geoJSON(j.geometry,{style:{color:'#2e9df4',weight:6,opacity:.88}}).addTo(map);window.__gslV162RouteMarkers=L.layerGroup().addTo(map);j.places.forEach((p,i)=>L.circleMarker([p.lat,p.lon],{radius:7,color:'#fff',weight:2,fillColor:i===0?'#18c995':i===j.places.length-1?'#ef5656':'#f3c84b',fillOpacity:1}).bindTooltip(i===0?'Inicio':i===j.places.length-1?'Fin':`Parada ${i}`).addTo(window.__gslV162RouteMarkers));map.fitBounds(window.__gslV162RouteLayer.getBounds(),{padding:[25,25]});const near=(window.GSL_ROAD_INCIDENTS||[]).filter(x=>Number.isFinite(+x.lat)&&Number.isFinite(+x.lon)&&window.__gslV162RouteLayer.getBounds().pad(.10).contains([+x.lat,+x.lon]));const originLabel=$('routeOrigin')?.value||'Inicio',destLabel=$('routeDestination')?.value||'Fin';$('routeSummary').innerHTML=`<b>${Math.round(j.distanceKm).toLocaleString('es-PE')} km</b> · <b>${(j.durationMin/60).toFixed(1)} h</b> estimadas · <b>${near.length}</b> incidencias cercanas al corredor. <a target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${encodeURIComponent(destination)}">Abrir navegación ↗</a>`;window.setContextLegend?.('roads',{title:'Ruta seleccionada',source:'OSRM + GeoSismosLatam',situation:`${originLabel} → ${destLabel}`,variable:'Ruta / tiempo / incidencias',unit:'km · horas',horizon:'Actual',intro:'Ruta vial estimada entre los puntos elegidos.',items:[['#18c995','circle','Inicio','Punto de salida.'],['#2e9df4','line','Ruta','Recorrido vial calculado.'],['#ef5656','circle','Fin','Destino.'],['#e64646','circle','Incidencias','Reportes cercanos al corredor.']]});}catch(e){$('routeSummary').textContent='No se pudo calcular la ruta entre esos puntos. Verifica que ambos estén conectados por una vía transitable.';}}
function useRouteForFreight(){const o=$('freightOrigin'),d=$('freightDestination');if(!o||!d)return;o.value=routeArg('routeOrigin',RS.start);d.value=routeArg('routeDestination',RS.end);o.dispatchEvent(new Event('change',{bubbles:true}));d.dispatchEvent(new Event('change',{bubbles:true}));$('routeSummary').textContent='Origen y destino copiados a la Calculadora Experimental de Flete.';}
function upgradePlanner(){const old=document.querySelector('.route-planner');if(!old||old.dataset.v162==='1')return;old.dataset.v162='1';old.className='route-planner-v162';old.innerHTML=`<div class="route-grid-v162"><div class="route-point-v162"><div class="route-point-title"><b>📍 PUNTO DE INICIO</b><span class="route-badge start">SALIDA</span></div><div class="route-search-row"><input id="routeOrigin" autocomplete="off" placeholder="Buscar calle, lugar, restaurante, hotel, plaza, centro comercial, negocio, distrito…"><button id="routeUseGps" class="btn">⌖ GPS</button><button class="btn pick-map-btn" data-kind="start">◎ MARCAR EN MAPA</button></div><div id="routeOriginSuggestions" class="route-suggestions"></div></div><div class="route-point-v162"><div class="route-point-title"><b>🏁 PUNTO FINAL</b><span class="route-badge end">DESTINO</span></div><div class="route-search-row"><input id="routeDestination" autocomplete="off" placeholder="Buscar calle, lugar, restaurante, hotel, plaza, centro comercial, negocio, distrito…"><button id="routeSearchDestination" class="btn">⌕ BUSCAR</button><button class="btn pick-map-btn" data-kind="end">◎ MARCAR EN MAPA</button></div><div id="routeDestinationSuggestions" class="route-suggestions"></div></div></div><div class="route-map-mode"><span id="routePickHint" class="route-pick-hint">Puedes buscar un lugar, usar GPS o marcar inicio y fin directamente sobre el mapa.</span></div><div id="routeStops" class="route-stops"></div><div class="route-actions-v162"><button id="routeAddStop" class="btn">+ PARADA</button><button id="routeDraw" class="btn primary">TRAZAR RUTA</button><button id="routeToFreight" class="btn">⇢ USAR EN FLETE</button><button id="routeClear" class="btn">LIMPIAR</button></div><div id="routeSummary" class="route-summary">Selecciona el inicio y el destino. También puedes marcarlos con un clic directamente en el mapa.</div><div class="route-quick-note">La búsqueda admite calles, direcciones, restaurantes, hoteles, plazas, centros comerciales, mercados, terminales, negocios y otros puntos de interés. Con Google Places configurado se usa su base; sin clave se utiliza un respaldo público de menor alcance.</div>`;
wireSearch('start');wireSearch('end');$('routeUseGps').onclick=useGps;$('routeSearchDestination').onclick=()=>searchPlaces('end',$('routeDestination').value.trim());document.querySelectorAll('.pick-map-btn').forEach(b=>b.onclick=()=>pickMap(b.dataset.kind));$('routeDraw').onclick=drawRoute;$('routeToFreight').onclick=useRouteForFreight;$('routeAddStop').onclick=()=>{const row=document.createElement('div');row.className='route-stop-row';row.innerHTML=`<input class="route-stop-input" placeholder="Parada intermedia: distrito / ciudad / lugar"><button class="btn">×</button>`;row.querySelector('button').onclick=()=>row.remove();$('routeStops').appendChild(row)};$('routeClear').onclick=()=>{['routeOrigin','routeDestination'].forEach(id=>{if($(id)){ $(id).value='';$(id).dataset.coord='';}});RS.start=RS.end=null;const map=window.GSL_ROAD_MAP;['startLayer','endLayer'].forEach(k=>{if(RS[k]&&map)map.removeLayer(RS[k]);RS[k]=null});if(window.__gslV162RouteLayer&&map)map.removeLayer(window.__gslV162RouteLayer);if(window.__gslV162RouteMarkers&&map)map.removeLayer(window.__gslV162RouteMarkers);$('routeSummary').textContent='Selecciona el inicio y el destino.';clearMode();};bindMapPicker();}
function waitRoad(){upgradePlanner();bindMapPicker();const btn=document.querySelector('[data-view="roads"]');btn?.addEventListener('click',()=>setTimeout(()=>{upgradePlanner();bindMapPicker();window.GSL_ROAD_MAP?.invalidateSize()},250));}
document.addEventListener('DOMContentLoaded',()=>setTimeout(waitRoad,400));
})();
